name: Lint and test TS
on: [pull_request]

jobs:
  test-lint-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn tslint
        shell: bash
      - name: Test
        run: yarn test
        shell: bash
